### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: com.company.FTPCSCLoader.SCardEstablishContext(IIII)I

### ISSUE THREAD

**Issue by rustem-s** [FeitianSmartcardReader/R301#2]
Hello!

I run java example SimplePCSC, press button SCardListReaders, and return error:
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: com.company.FTPCSCLoader.SCardEstablishContext(IIII)I
	at com.company.FTPCSCLoader.SCardEstablishContext(Native Method)
	at com.company.FTPCSCLoader.jSCardEstablishContext(FTPCSCLoader.java:32)
...

In Windows Device manager Card reader is exists.

**Comment by rustem-s** [comment]
I found the cause of the problem. In my project, Java classes were placed in a Java package. I moved the java classes to the root of the project and removed the java package.
